name: Practice
api: 5.0.0
version: 1.0.0
src-namespace-prefix: Nayuki
main: Nayuki\PracticeCore
author: https://github.com/Kuuuuuuuu
permissions:
  practice.command:
    default: op
  restart.command:
    default: op
  settag.command:
    default: op
  tban.command:
    default: op
  tcheck.command:
    default: op
  hologram.command:
    default: op
  default.command:
    default: true